### PR TITLE
add license field

### PR DESCRIPTION
**Pull request by soenkehahn**
@redSlug, @lucy-zhang, @caroline-lin: I'm adding a license to this code and since you all contributed to it, I'm pinging you. Are you fine with publishing your contributions under `GPL-3.0-or-later`?

### CODE REVIEW

**Comment by wwwaldo** [comment]
Yes, this is fine with me!

**Comment by thoszhang** [comment]
Me too

**Comment by redSlug** [comment]
Approved

**Review by redSlug — APPROVED** [review]

**Comment by soenkehahn** [comment]
Thanks!

**Pull request merged**
